### ISSUE TITLE
ContactInformation model should not have unique fields

### ISSUE THREAD

**Issue by pradumangoyal** [IMGIITRoorkee/omniport-backend-formula-one#8]
https://github.com/IMGIITRoorkee/omniport-backend-formula-one/blob/master/models/generics/contact_information.py

The `ContactInformation` model should not have unique fields. The reason being the way this model is written. It is meant to be a generic model which can be linked to any type of model entity in the Omniport. We can assume surely that there can't be two `Person` with the same email id, but we can't for the other entities. For example, IMG is a `Group` (Groups service) as well as `MaintainerGroup` (Maintainer site service) which are same so bears the same email id.

Although there is an issue because these email ids are used in the login so we lifting up the unique completely will make `getUser()` function error-prone.

*Suggestion*
In my opinion, one solution can be to put `unique_together` constraint with the entity_type instead of `unique` constraints. And also then we can filter out `ContactInformation` where `entity_type` is `Person` in the `getUser()` function.

**Comment by pradumangoyal** [comment]
I was thinking to just have a discussion on them, there are some good-first-issues and we have a lot of beginners (in omniport) coming soon. These issues will be good exposure for them.

**Comment by ruddi10** [comment]
Kindly assign it to me

**Comment by pradumangoyal** [comment]
Yes, go ahead!

**Comment by pradumangoyal** [comment]
@ruddi10 any updates?
